#to be replaced by envirvonment variables in a production setting
spring.datasource.url=jdbc:postgresql://localhost:5432/diary_db
spring.datasource.username=rw091402
spring.datasource.password=0914
spring.datasource.driver-class-name=org.postgresql.Driver

#remember to switch back to update/validate 
spring.jpa.hibernate.ddl-auto=create 
spring.jpa.show-sql=true
jwt.secret=there are consequences for killing a god