spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

#remember to switch back to update/validate
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
jwt.secret=${JWT_SECRET}